<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 12 Data Visualization | Economics of Public and Social Issues</title>
  <meta name="description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2024." />
  <meta name="generator" content="bookdown 0.40 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 12 Data Visualization | Economics of Public and Social Issues" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2024." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 12 Data Visualization | Economics of Public and Social Issues" />
  
  <meta name="twitter:description" content="This is the website for the course ECO 3253 at UTSA, taught in the Fall of 2024." />
  

<meta name="author" content="Jonathan Moreno-Medina" />


<meta name="date" content="2024-08-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="getting-started.html"/>
<link rel="next" href="wrangling.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Eco of Public and Social Issues (ECO 3253), Fall 2022</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#aboutme"><i class="fa fa-check"></i>About me</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#organization-of-this-site"><i class="fa fa-check"></i>Organization of this site</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#data-driven-course"><i class="fa fa-check"></i>Data-driven course</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#topics-to-be-covered"><i class="fa fa-check"></i>Topics to be covered</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#statistical-tools"><i class="fa fa-check"></i>Statistical tools</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#economic-concepts"><i class="fa fa-check"></i>Economic Concepts</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#projects"><i class="fa fa-check"></i>Projects</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#faqs"><i class="fa fa-check"></i>FAQs</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="schedule.html"><a href="schedule.html"><i class="fa fa-check"></i>Updated Schedule</a></li>
<li class="part"><span><b>I Ec. &amp; Soc. Issues</b></span></li>
<li class="chapter" data-level="1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html"><i class="fa fa-check"></i><b>1</b> Upward Mobility in the US</a>
<ul>
<li class="chapter" data-level="1.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#parental-and-children-income-rank"><i class="fa fa-check"></i><b>1.1</b> Parental and children income rank</a></li>
<li class="chapter" data-level="1.2" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#interpreting-the-regression-line"><i class="fa fa-check"></i><b>1.2</b> Interpreting the regression line</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#percentiles"><i class="fa fa-check"></i><b>1.2.1</b> Percentiles</a></li>
<li class="chapter" data-level="1.2.2" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#what-is-a-tract"><i class="fa fa-check"></i><b>1.2.2</b> What is a tract?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#geographic-variation-in-upward-mobility-by-commuting-zone"><i class="fa fa-check"></i><b>1.3</b> Geographic Variation in Upward Mobility by Commuting Zone</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#adjustments-for-cost-of-living"><i class="fa fa-check"></i><b>1.3.1</b> Adjustments for cost of living</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="lec1_geomobility.html"><a href="lec1_geomobility.html#local-area-variation-in-upward-mobility-los-angeles-ca"><i class="fa fa-check"></i><b>1.4</b> Local Area Variation in Upward Mobility: Los Angeles, CA</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html"><i class="fa fa-check"></i><b>2</b> The Causal Effect of Neighborhoods</a>
<ul>
<li class="chapter" data-level="2.1" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#introduction"><i class="fa fa-check"></i><b>2.1</b> Introduction</a></li>
<li class="chapter" data-level="2.2" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#causal-effects-of-neighborhoods-vs.-sorting"><i class="fa fa-check"></i><b>2.2</b> Causal Effects of Neighborhoods vs. Sorting</a></li>
<li class="chapter" data-level="2.3" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#identifying-causal-effects-of-neighborhoods"><i class="fa fa-check"></i><b>2.3</b> Identifying Causal Effects of Neighborhoods</a></li>
<li class="chapter" data-level="2.4" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#stating-and-assessing-the-identification-assumption-for-the-movers-research-design"><i class="fa fa-check"></i><b>2.4</b> Stating and assessing the identification assumption for the movers research design</a></li>
<li class="chapter" data-level="2.5" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#why-does-upward-mobility-differ-across-areas"><i class="fa fa-check"></i><b>2.5</b> Why Does Upward Mobility Differ Across Areas?</a></li>
<li class="chapter" data-level="2.6" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#the-five-strongest-correlates-of-upward-mobility"><i class="fa fa-check"></i><b>2.6</b> The Five Strongest Correlates of Upward Mobility</a></li>
<li class="chapter" data-level="2.7" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#policy-interest-in-increasing-upward-mobility"><i class="fa fa-check"></i><b>2.7</b> Policy Interest in Increasing Upward Mobility</a></li>
<li class="chapter" data-level="2.8" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#policies-to-improve-upward-mobility"><i class="fa fa-check"></i><b>2.8</b> Policies to Improve Upward Mobility</a></li>
<li class="chapter" data-level="2.9" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#affordable-housing-policies-in-the-united-states"><i class="fa fa-check"></i><b>2.9</b> Affordable Housing Policies in the United States</a></li>
<li class="chapter" data-level="2.10" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#a-framework-for-studying-the-effects-of-housing-vouchers"><i class="fa fa-check"></i><b>2.10</b> A Framework for Studying the Effects of Housing Vouchers</a></li>
<li class="chapter" data-level="2.11" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#randomized-experiments"><i class="fa fa-check"></i><b>2.11</b> Randomized Experiments</a></li>
<li class="chapter" data-level="2.12" data-path="lec2_causaleffect.html"><a href="lec2_causaleffect.html#non-compliance-in-randomized-experiments"><i class="fa fa-check"></i><b>2.12</b> Non-Compliance in Randomized Experiments</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html"><i class="fa fa-check"></i><b>3</b> Policies to Increase Upward Mobility</a>
<ul>
<li class="chapter" data-level="3.1" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#the-moving-to-opportunity-experiment"><i class="fa fa-check"></i><b>3.1</b> The Moving to Opportunity Experiment</a></li>
<li class="chapter" data-level="3.2" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#reevaluating-the-moving-to-opportunities-experiment-with-a-big-data-approach"><i class="fa fa-check"></i><b>3.2</b> Reevaluating the Moving to Opportunities Experiment with a Big Data Approach</a></li>
<li class="chapter" data-level="3.3" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#the-three-limits-of-randomized-controlled-trials"><i class="fa fa-check"></i><b>3.3</b> The Three Limits of Randomized Controlled Trials</a></li>
<li class="chapter" data-level="3.4" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#how-quasi-experimental-methods-can-address-randomized-controlled-trial-limitations"><i class="fa fa-check"></i><b>3.4</b> How Quasi-Experimental Methods can Address Randomized Controlled Trial Limitations</a></li>
<li class="chapter" data-level="3.5" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#implications-for-housing-voucher-policies"><i class="fa fa-check"></i><b>3.5</b> Implications for Housing Voucher Policies</a></li>
<li class="chapter" data-level="3.6" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#the-stability-of-historical-measures-of-opportunity"><i class="fa fa-check"></i><b>3.6</b> The Stability of Historical Measures of Opportunity</a></li>
<li class="chapter" data-level="3.7" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#the-creating-moves-to-opportunity-pilot-in-seattle"><i class="fa fa-check"></i><b>3.7</b> The Creating Moves to Opportunity Pilot in Seattle</a></li>
<li class="chapter" data-level="3.8" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#three-concerns-about-the-cmto-approach"><i class="fa fa-check"></i><b>3.8</b> Three Concerns about the CMTO Approach</a></li>
<li class="chapter" data-level="3.9" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#the-idea-behind-place-based-investment"><i class="fa fa-check"></i><b>3.9</b> The Idea Behind Place Based Investment</a></li>
<li class="chapter" data-level="3.10" data-path="lec3_mto-placebased.html"><a href="lec3_mto-placebased.html#place-based-intervention-policies"><i class="fa fa-check"></i><b>3.10</b> Place Based Intervention Policies</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html"><i class="fa fa-check"></i><b>4</b> The American Dream in Historical Perspective</a>
<ul>
<li class="chapter" data-level="4.1" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#a-historical-perspective-on-the-american-dream"><i class="fa fa-check"></i><b>4.1</b> A Historical Perspective on the American Dream</a></li>
<li class="chapter" data-level="4.2" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#measuring-the-american-dream"><i class="fa fa-check"></i><b>4.2</b> Measuring the American Dream</a></li>
<li class="chapter" data-level="4.3" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#what-policies-can-increase-economic-mobility"><i class="fa fa-check"></i><b>4.3</b> What Policies Can Increase Economic Mobility?</a></li>
<li class="chapter" data-level="4.4" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#policies-to-revive-absolute-mobility"><i class="fa fa-check"></i><b>4.4</b> Policies to Revive Absolute Mobility</a></li>
<li class="chapter" data-level="4.5" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#trends-in-upward-mobility-international-comparisons"><i class="fa fa-check"></i><b>4.5</b> Trends in Upward Mobility: International Comparisons</a></li>
<li class="chapter" data-level="4.6" data-path="lec4_mob-hist-int.html"><a href="lec4_mob-hist-int.html#restoring-the-american-dream-two-approaches"><i class="fa fa-check"></i><b>4.6</b> Restoring the American Dream: Two Approaches</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html"><i class="fa fa-check"></i><b>5</b> Higher Education and Upward Mobility</a>
<ul>
<li class="chapter" data-level="5.1" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#education-and-upward-mobility"><i class="fa fa-check"></i><b>5.1</b> Education and Upward Mobility</a></li>
<li class="chapter" data-level="5.2" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#how-do-colleges-shape-income-mobility-in-the-u.s."><i class="fa fa-check"></i><b>5.2</b> How do Colleges Shape Income Mobility in the U.S.?</a></li>
<li class="chapter" data-level="5.3" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#effect-of-the-higher-education-system-on-mobility"><i class="fa fa-check"></i><b>5.3</b> Effect of the Higher Education System on Mobility</a></li>
<li class="chapter" data-level="5.4" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#estimating-the-three-parameters-data."><i class="fa fa-check"></i><b>5.4</b> Estimating the Three Parameters: Data.</a></li>
<li class="chapter" data-level="5.5" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#parents-income-distributions-by-college-income-segregation-in-the-american-higher-education-system.-measuring-parents-income."><i class="fa fa-check"></i><b>5.5</b> Parents’ Income Distributions by College: Income Segregation in the American Higher Education System. Measuring Parents’ Income.</a></li>
<li class="chapter" data-level="5.6" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#trends-in-income-segregation"><i class="fa fa-check"></i><b>5.6</b> Trends in Income Segregation</a></li>
<li class="chapter" data-level="5.7" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#outcomes-students-earnings-distributions"><i class="fa fa-check"></i><b>5.7</b> Outcomes: Students’ Earnings Distributions</a></li>
<li class="chapter" data-level="5.8" data-path="lec5_mob-ed.html"><a href="lec5_mob-ed.html#differences-in-mobility-rates-across-colleges"><i class="fa fa-check"></i><b>5.8</b> Differences in Mobility Rates Across Colleges</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html"><i class="fa fa-check"></i><b>6</b> The Causal Effect of Colleges</a>
<ul>
<li class="chapter" data-level="6.1" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#causal-effects-of-colleges"><i class="fa fa-check"></i><b>6.1</b> Causal Effects of Colleges</a></li>
<li class="chapter" data-level="6.2" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#estimating-the-causal-effects-of-colleges"><i class="fa fa-check"></i><b>6.2</b> Estimating the Causal Effects of Colleges</a></li>
<li class="chapter" data-level="6.3" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#regression-discontinuity-methods"><i class="fa fa-check"></i><b>6.3</b> Regression Discontinuity Methods</a></li>
<li class="chapter" data-level="6.4" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#zimmerman-study"><i class="fa fa-check"></i><b>6.4</b> Zimmerman Study</a></li>
<li class="chapter" data-level="6.5" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#causal-effects-of-colleges-1"><i class="fa fa-check"></i><b>6.5</b> Causal Effects of Colleges</a></li>
<li class="chapter" data-level="6.6" data-path="lec6_ed-higher.html"><a href="lec6_ed-higher.html#university-of-michigan-hail-experiment"><i class="fa fa-check"></i><b>6.6</b> University of Michigan HAIL Experiment</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="lec7_k12.html"><a href="lec7_k12.html"><i class="fa fa-check"></i><b>7</b> Primary Education</a>
<ul>
<li class="chapter" data-level="7.1" data-path="lec7_k12.html"><a href="lec7_k12.html#a-recap-of-the-discussion-on-the-causal-effects-of-college"><i class="fa fa-check"></i><b>7.1</b> A Recap of the Discussion on the Causal Effects of College</a></li>
<li class="chapter" data-level="7.2" data-path="lec7_k12.html"><a href="lec7_k12.html#questions-on-causal-effects-of-college"><i class="fa fa-check"></i><b>7.2</b> Questions on Causal Effects of College</a></li>
<li class="chapter" data-level="7.3" data-path="lec7_k12.html"><a href="lec7_k12.html#an-overview-of-the-k-12-system-in-the-us"><i class="fa fa-check"></i><b>7.3</b> An Overview of the K-12 System in the US</a></li>
<li class="chapter" data-level="7.4" data-path="lec7_k12.html"><a href="lec7_k12.html#do-test-scores-predict-long-run-outcomes"><i class="fa fa-check"></i><b>7.4</b> Do Test Scores Predict Long-Run Outcomes?</a></li>
<li class="chapter" data-level="7.5" data-path="lec7_k12.html"><a href="lec7_k12.html#making-test-scores-comparable"><i class="fa fa-check"></i><b>7.5</b> Making Test Scores Comparable</a></li>
<li class="chapter" data-level="7.6" data-path="lec7_k12.html"><a href="lec7_k12.html#achievement-gaps-in-test-scores-by-socioeconomic-status"><i class="fa fa-check"></i><b>7.6</b> Achievement Gaps in Test Scores by Socioeconomic Status</a></li>
<li class="chapter" data-level="7.7" data-path="lec7_k12.html"><a href="lec7_k12.html#two-policy-paradigms"><i class="fa fa-check"></i><b>7.7</b> Two Policy Paradigms</a></li>
<li class="chapter" data-level="7.8" data-path="lec7_k12.html"><a href="lec7_k12.html#government-based-solutions-to-improving-schools"><i class="fa fa-check"></i><b>7.8</b> Government Based Solutions to Improving Schools</a></li>
<li class="chapter" data-level="7.9" data-path="lec7_k12.html"><a href="lec7_k12.html#the-effect-of-class-size"><i class="fa fa-check"></i><b>7.9</b> The Effect of Class Size</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="lec7_k12.html"><a href="lec7_k12.html#the-tennessee-star-experiment"><i class="fa fa-check"></i><b>7.9.1</b> The Tennessee Star Experiment</a></li>
</ul></li>
<li class="chapter" data-level="7.10" data-path="lec7_k12.html"><a href="lec7_k12.html#class-size-cutoffs-in-sweden"><i class="fa fa-check"></i><b>7.10</b> Class Size Cutoffs in Sweden</a></li>
<li class="chapter" data-level="7.11" data-path="lec7_k12.html"><a href="lec7_k12.html#questions-on-primary-education"><i class="fa fa-check"></i><b>7.11</b> Questions on Primary Education</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html"><i class="fa fa-check"></i><b>8</b> Teachers and Charter School</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#using-big-data-to-study-teachers-impacts"><i class="fa fa-check"></i><b>8.1</b> Using Big Data to Study Teachers’ Impacts</a></li>
<li class="chapter" data-level="8.2" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#measuring-teacher-quality-test-score-based-metrics"><i class="fa fa-check"></i><b>8.2</b> Measuring Teacher Quality: Test-Score Based Metrics</a></li>
<li class="chapter" data-level="8.3" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#debate-about-teacher-value-added-measures"><i class="fa fa-check"></i><b>8.3</b> Debate about Teacher Value-Added Measures</a></li>
<li class="chapter" data-level="8.4" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#measuring-the-impacts-of-teachers"><i class="fa fa-check"></i><b>8.4</b> Measuring the Impacts of Teachers</a></li>
<li class="chapter" data-level="8.5" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#a-quasi-experiment-entry-of-a-high-value-added-teacher"><i class="fa fa-check"></i><b>8.5</b> A Quasi-Experiment: Entry of a High Value-Added Teacher</a></li>
<li class="chapter" data-level="8.6" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#lesson-1-va-estimates-are-unbiased-measures-of-teacher-effectiveness"><i class="fa fa-check"></i><b>8.6</b> Lesson 1: VA Estimates are Unbiased Measures of Teacher Effectiveness</a></li>
<li class="chapter" data-level="8.7" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#lesson-2-va-estimates-based-on-test-scores-predict-teachers-long-term-impacts"><i class="fa fa-check"></i><b>8.7</b> Lesson 2: VA Estimates Based on Test Scores Predict Teachers’ Long Term Impacts</a></li>
<li class="chapter" data-level="8.8" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#lesson-3-va-estimates-based-on-a-few-years-of-data-are-sufficiently-reliable-to-generate-large-gains-on-average"><i class="fa fa-check"></i><b>8.8</b> Lesson 3: VA Estimates Based on a Few Years of Data are Sufficiently Reliable to Generate Large Gains on Average</a></li>
<li class="chapter" data-level="8.9" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#policy-impacts"><i class="fa fa-check"></i><b>8.9</b> Policy Impacts</a></li>
<li class="chapter" data-level="8.10" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#market-based-solutions-charter-schools"><i class="fa fa-check"></i><b>8.10</b> Market Based-Solutions: Charter Schools</a></li>
<li class="chapter" data-level="8.11" data-path="lec8_teachers-charters.html"><a href="lec8_teachers-charters.html#do-charter-schools-work"><i class="fa fa-check"></i><b>8.11</b> Do Charter Schools Work?</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html"><i class="fa fa-check"></i><b>9</b> Racial Disparities in Economic Opportunity</a>
<ul>
<li class="chapter" data-level="9.1" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#introduction-1"><i class="fa fa-check"></i><b>9.1</b> Introduction</a></li>
<li class="chapter" data-level="9.2" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#theories-of-racial-disparities"><i class="fa fa-check"></i><b>9.2</b> Theories of Racial Disparities</a></li>
<li class="chapter" data-level="9.3" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#an-intergenerational-perspective-on-racial-disparities"><i class="fa fa-check"></i><b>9.3</b> An Intergenerational Perspective on Racial Disparities</a></li>
<li class="chapter" data-level="9.4" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#intergenerational-mobility-in-the-u.s."><i class="fa fa-check"></i><b>9.4</b> Intergenerational Mobility in the U.S.</a></li>
<li class="chapter" data-level="9.5" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#intergenerational-mobility-for-whites-vs.-blacks"><i class="fa fa-check"></i><b>9.5</b> Intergenerational Mobility for Whites vs. Blacks</a></li>
<li class="chapter" data-level="9.6" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#steady-states"><i class="fa fa-check"></i><b>9.6</b> Steady States</a></li>
<li class="chapter" data-level="9.7" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#other-racial-disparities"><i class="fa fa-check"></i><b>9.7</b> Other Racial Disparities</a></li>
<li class="chapter" data-level="9.8" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#gender-differences-in-racial-gaps"><i class="fa fa-check"></i><b>9.8</b> Gender Differences in Racial Gaps</a></li>
<li class="chapter" data-level="9.9" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#explaining-the-black-white-intergenerational-income-gap-family-level-factors"><i class="fa fa-check"></i><b>9.9</b> Explaining the Black-White Intergenerational Income Gap: Family Level Factors</a></li>
<li class="chapter" data-level="9.10" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#the-role-of-environmental-factors"><i class="fa fa-check"></i><b>9.10</b> The Role of Environmental Factors</a></li>
<li class="chapter" data-level="9.11" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#neighborhood-environments-and-the-black-white-gap"><i class="fa fa-check"></i><b>9.11</b> Neighborhood Environments and the Black-White Gap</a></li>
<li class="chapter" data-level="9.12" data-path="lec9_race-ineq.html"><a href="lec9_race-ineq.html#conclusions"><i class="fa fa-check"></i><b>9.12</b> Conclusions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html"><i class="fa fa-check"></i><b>10</b> Improving Judicial Decisions</a>
<ul>
<li class="chapter" data-level="10.1" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#motivation-bias-in-human-decision-making"><i class="fa fa-check"></i><b>10.1</b> Motivation: Bias in Human Decision Making</a></li>
<li class="chapter" data-level="10.2" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#decisions-to-jail-vs.-release-defendants"><i class="fa fa-check"></i><b>10.2</b> Decisions to Jail vs. Release Defendants</a></li>
<li class="chapter" data-level="10.3" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#data-used-for-empirical-analysis"><i class="fa fa-check"></i><b>10.3</b> Data Used for Empirical Analysis</a></li>
<li class="chapter" data-level="10.4" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#methodology"><i class="fa fa-check"></i><b>10.4</b> Methodology</a></li>
<li class="chapter" data-level="10.5" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#comparing-machine-predictions-to-human-predictions"><i class="fa fa-check"></i><b>10.5</b> Comparing Machine Predictions to Human Predictions</a></li>
<li class="chapter" data-level="10.6" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#predictive-policing"><i class="fa fa-check"></i><b>10.6</b> Predictive Policing</a></li>
<li class="chapter" data-level="10.7" data-path="lec10_criminal-justice.html"><a href="lec10_criminal-justice.html#conclusion"><i class="fa fa-check"></i><b>10.7</b> Conclusion</a></li>
</ul></li>
<li class="part"><span><b>II Tools</b></span></li>
<li class="chapter" data-level="11" data-path="getting-started.html"><a href="getting-started.html"><i class="fa fa-check"></i><b>11</b> Very Brief Intro to Data in R</a>
<ul>
<li class="chapter" data-level="11.1" data-path="getting-started.html"><a href="getting-started.html#why-r-again"><i class="fa fa-check"></i><b>11.1</b> Why R again?</a>
<ul>
<li class="chapter" data-level="11.1.1" data-path="getting-started.html"><a href="getting-started.html#why-are-we-learning-r-i-wanted-to-learn-about-economics-of-public-and-social-issues"><i class="fa fa-check"></i><b>11.1.1</b> Why are we learning R? I wanted to learn about economics of public and social issues…</a></li>
<li class="chapter" data-level="11.1.2" data-path="getting-started.html"><a href="getting-started.html#ok-but-why-r"><i class="fa fa-check"></i><b>11.1.2</b> Ok, but why R?</a></li>
<li class="chapter" data-level="11.1.3" data-path="getting-started.html"><a href="getting-started.html#added-benefits-of-learning-r"><i class="fa fa-check"></i><b>11.1.3</b> Added benefits of learning R</a></li>
</ul></li>
<li class="chapter" data-level="11.2" data-path="getting-started.html"><a href="getting-started.html#key-concepts-before-we-start"><i class="fa fa-check"></i><b>11.2</b> Key concepts before we start:</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="getting-started.html"><a href="getting-started.html#r-rstudio"><i class="fa fa-check"></i><b>11.2.1</b> What are R and RStudio?</a></li>
<li class="chapter" data-level="11.2.2" data-path="getting-started.html"><a href="getting-started.html#r-and-rstudio-in-your-computer-or-in-the-cloud-the-benefit-of-posit-cloud"><i class="fa fa-check"></i><b>11.2.2</b> R and RStudio: In your computer or in the cloud? The benefit of Posit Cloud</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="getting-started.html"><a href="getting-started.html#lets-open-r"><i class="fa fa-check"></i><b>11.3</b> Let’s open R!</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="getting-started.html"><a href="getting-started.html#rstudio-in-posit-cloud"><i class="fa fa-check"></i><b>11.3.1</b> RStudio in Posit cloud</a></li>
<li class="chapter" data-level="11.3.2" data-path="getting-started.html"><a href="getting-started.html#using-r-via-rstudio-in-posit-cloud"><i class="fa fa-check"></i><b>11.3.2</b> Using R via RStudio in Posit Cloud</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="getting-started.html"><a href="getting-started.html#code"><i class="fa fa-check"></i><b>11.4</b> How do I code in R?</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="getting-started.html"><a href="getting-started.html#programming-concepts"><i class="fa fa-check"></i><b>11.4.1</b> Basic programming concepts and terminology</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="getting-started.html"><a href="getting-started.html#in-class-exercise"><i class="fa fa-check"></i><b>11.5</b> In Class Exercise</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="getting-started.html"><a href="getting-started.html#errors-warnings-and-messages"><i class="fa fa-check"></i><b>11.5.1</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="11.5.2" data-path="getting-started.html"><a href="getting-started.html#tips-on-learning-to-code"><i class="fa fa-check"></i><b>11.5.2</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="getting-started.html"><a href="getting-started.html#packages"><i class="fa fa-check"></i><b>11.6</b> What are R packages?</a>
<ul>
<li class="chapter" data-level="11.6.1" data-path="getting-started.html"><a href="getting-started.html#package-installation"><i class="fa fa-check"></i><b>11.6.1</b> Package installation</a></li>
<li class="chapter" data-level="11.6.2" data-path="getting-started.html"><a href="getting-started.html#package-loading"><i class="fa fa-check"></i><b>11.6.2</b> Package loading</a></li>
<li class="chapter" data-level="11.6.3" data-path="getting-started.html"><a href="getting-started.html#package-use"><i class="fa fa-check"></i><b>11.6.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="11.7" data-path="getting-started.html"><a href="getting-started.html#hands-on-exercise"><i class="fa fa-check"></i><b>11.7</b> Hands-on exercise!</a>
<ul>
<li class="chapter" data-level="11.7.1" data-path="getting-started.html"><a href="getting-started.html#mobilitydata"><i class="fa fa-check"></i><b>11.7.1</b> Explore your first dataset: economic mobility in the US</a></li>
<li class="chapter" data-level="11.7.2" data-path="getting-started.html"><a href="getting-started.html#economic-mobility-data"><i class="fa fa-check"></i><b>11.7.2</b> Economic mobility data</a></li>
<li class="chapter" data-level="11.7.3" data-path="getting-started.html"><a href="getting-started.html#atlas-data-frame"><i class="fa fa-check"></i><b>11.7.3</b> <code>atlas</code> data frame</a></li>
<li class="chapter" data-level="11.7.4" data-path="getting-started.html"><a href="getting-started.html#exploredataframes"><i class="fa fa-check"></i><b>11.7.4</b> Exploring data frames</a></li>
</ul></li>
<li class="chapter" data-level="11.8" data-path="getting-started.html"><a href="getting-started.html#conclusion-1"><i class="fa fa-check"></i><b>11.8</b> Conclusion</a>
<ul>
<li class="chapter" data-level="11.8.1" data-path="getting-started.html"><a href="getting-started.html#additional-resources"><i class="fa fa-check"></i><b>11.8.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="12" data-path="viz.html"><a href="viz.html"><i class="fa fa-check"></i><b>12</b> Data Visualization</a>
<ul>
<li class="chapter" data-level="" data-path="viz.html"><a href="viz.html#needed-data-and-packages"><i class="fa fa-check"></i>Needed data and packages</a></li>
<li class="chapter" data-level="12.1" data-path="viz.html"><a href="viz.html#grammarofgraphics"><i class="fa fa-check"></i><b>12.1</b> The Grammar of Graphics</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="viz.html"><a href="viz.html#components-of-the-grammar"><i class="fa fa-check"></i><b>12.1.1</b> Components of the Grammar</a></li>
<li class="chapter" data-level="12.1.2" data-path="viz.html"><a href="viz.html#gapminder"><i class="fa fa-check"></i><b>12.1.2</b> Gapminder data</a></li>
<li class="chapter" data-level="12.1.3" data-path="viz.html"><a href="viz.html#other-components"><i class="fa fa-check"></i><b>12.1.3</b> Other components</a></li>
<li class="chapter" data-level="12.1.4" data-path="viz.html"><a href="viz.html#ggplot2-package"><i class="fa fa-check"></i><b>12.1.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="viz.html"><a href="viz.html#FiveNG"><i class="fa fa-check"></i><b>12.2</b> Three Important Graphs -</a></li>
<li class="chapter" data-level="12.3" data-path="viz.html"><a href="viz.html#scatterplots"><i class="fa fa-check"></i><b>12.3</b> Scatterplots</a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="viz.html"><a href="viz.html#geompoint"><i class="fa fa-check"></i><b>12.3.1</b> Scatterplots via geom_point</a></li>
<li class="chapter" data-level="12.3.2" data-path="viz.html"><a href="viz.html#overplotting"><i class="fa fa-check"></i><b>12.3.2</b> Over-plotting</a></li>
<li class="chapter" data-level="12.3.3" data-path="viz.html"><a href="viz.html#summary"><i class="fa fa-check"></i><b>12.3.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="viz.html"><a href="viz.html#histograms"><i class="fa fa-check"></i><b>12.4</b> Histograms</a>
<ul>
<li class="chapter" data-level="12.4.1" data-path="viz.html"><a href="viz.html#geomhistogram"><i class="fa fa-check"></i><b>12.4.1</b> Histograms via geom_histogram</a></li>
<li class="chapter" data-level="12.4.2" data-path="viz.html"><a href="viz.html#adjustbins"><i class="fa fa-check"></i><b>12.4.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="12.4.3" data-path="viz.html"><a href="viz.html#summary-1"><i class="fa fa-check"></i><b>12.4.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.5" data-path="viz.html"><a href="viz.html#geombar"><i class="fa fa-check"></i><b>12.5</b> Barplots</a>
<ul>
<li class="chapter" data-level="12.5.1" data-path="viz.html"><a href="viz.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>12.5.1</b> Barplots via geom_bar or geom_col</a></li>
<li class="chapter" data-level="12.5.2" data-path="viz.html"><a href="viz.html#summary-2"><i class="fa fa-check"></i><b>12.5.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="12.6" data-path="viz.html"><a href="viz.html#conclusion-2"><i class="fa fa-check"></i><b>12.6</b> Conclusion</a>
<ul>
<li class="chapter" data-level="12.6.1" data-path="viz.html"><a href="viz.html#summary-table"><i class="fa fa-check"></i><b>12.6.1</b> Summary table</a></li>
<li class="chapter" data-level="12.6.2" data-path="viz.html"><a href="viz.html#argument-specification"><i class="fa fa-check"></i><b>12.6.2</b> Argument specification</a></li>
<li class="chapter" data-level="12.6.3" data-path="viz.html"><a href="viz.html#additional-resources-1"><i class="fa fa-check"></i><b>12.6.3</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="13" data-path="wrangling.html"><a href="wrangling.html"><i class="fa fa-check"></i><b>13</b> Data Wrangling</a>
<ul>
<li class="chapter" data-level="" data-path="wrangling.html"><a href="wrangling.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="13.1" data-path="wrangling.html"><a href="wrangling.html#piping"><i class="fa fa-check"></i><b>13.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="13.2" data-path="wrangling.html"><a href="wrangling.html#filter"><i class="fa fa-check"></i><b>13.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="13.3" data-path="wrangling.html"><a href="wrangling.html#mutate"><i class="fa fa-check"></i><b>13.3</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="13.4" data-path="wrangling.html"><a href="wrangling.html#other-verbs"><i class="fa fa-check"></i><b>13.4</b> Other verbs</a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="wrangling.html"><a href="wrangling.html#select"><i class="fa fa-check"></i><b>13.4.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="13.4.2" data-path="wrangling.html"><a href="wrangling.html#rename"><i class="fa fa-check"></i><b>13.4.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="13.4.3" data-path="wrangling.html"><a href="wrangling.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>13.4.3</b> <code>top_n</code> values of a variable</a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="wrangling.html"><a href="wrangling.html#conclusion-3"><i class="fa fa-check"></i><b>13.5</b> Conclusion</a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="wrangling.html"><a href="wrangling.html#additional-resources-2"><i class="fa fa-check"></i><b>13.5.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="14" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>14</b> Simple and Multivariate Regression</a>
<ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="14.1" data-path="regression.html"><a href="regression.html#model1"><i class="fa fa-check"></i><b>14.1</b> One numerical explanatory variable</a>
<ul>
<li class="chapter" data-level="14.1.1" data-path="regression.html"><a href="regression.html#model1EDA"><i class="fa fa-check"></i><b>14.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="14.1.2" data-path="regression.html"><a href="regression.html#model1table"><i class="fa fa-check"></i><b>14.1.2</b> Simple linear regression</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="regression.html"><a href="regression.html#related-topics"><i class="fa fa-check"></i><b>14.2</b> Related topics</a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="regression.html"><a href="regression.html#correlationcoefficient"><i class="fa fa-check"></i><b>14.2.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="14.2.2" data-path="regression.html"><a href="regression.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>14.2.2</b> Correlation is not necessarily causation</a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="regression.html"><a href="regression.html#model3"><i class="fa fa-check"></i><b>14.3</b> Two numerical explanatory variables</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="regression.html"><a href="regression.html#model3EDA"><i class="fa fa-check"></i><b>14.3.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="14.3.2" data-path="regression.html"><a href="regression.html#model3table"><i class="fa fa-check"></i><b>14.3.2</b> Regression plane</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="regression.html"><a href="regression.html#how-to-read-p-values"><i class="fa fa-check"></i><b>14.4</b> How to read p-values</a>
<ul>
<li class="chapter" data-level="14.4.1" data-path="regression.html"><a href="regression.html#an-example"><i class="fa fa-check"></i><b>14.4.1</b> An Example</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="regression.html"><a href="regression.html#conclusion-4"><i class="fa fa-check"></i><b>14.5</b> Conclusion</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="regression.html"><a href="regression.html#additional-resources-basic-regression"><i class="fa fa-check"></i><b>14.5.1</b> Additional resources</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="15" data-path="rmarkdown.html"><a href="rmarkdown.html"><i class="fa fa-check"></i><b>15</b> RMarkdown / Quarto output</a>
<ul>
<li class="chapter" data-level="15.1" data-path="rmarkdown.html"><a href="rmarkdown.html#how-to-create-an-output-file"><i class="fa fa-check"></i><b>15.1</b> How to create an output file</a>
<ul>
<li class="chapter" data-level="15.1.1" data-path="rmarkdown.html"><a href="rmarkdown.html#error-when-rendering-file"><i class="fa fa-check"></i><b>15.1.1</b> Error when rendering file</a></li>
</ul></li>
<li class="chapter" data-level="15.2" data-path="rmarkdown.html"><a href="rmarkdown.html#add-new-code"><i class="fa fa-check"></i><b>15.2</b> Add new code</a></li>
<li class="chapter" data-level="15.3" data-path="rmarkdown.html"><a href="rmarkdown.html#add-a-title"><i class="fa fa-check"></i><b>15.3</b> Add a title</a></li>
<li class="chapter" data-level="15.4" data-path="rmarkdown.html"><a href="rmarkdown.html#add-an-image"><i class="fa fa-check"></i><b>15.4</b> Add an image</a></li>
<li class="chapter" data-level="15.5" data-path="rmarkdown.html"><a href="rmarkdown.html#submit-your-work"><i class="fa fa-check"></i><b>15.5</b> Submit your work</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="appendixA.html"><a href="appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a>
<ul>
<li class="chapter" data-level="A.1" data-path="appendixA.html"><a href="appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a>
<ul>
<li class="chapter" data-level="A.1.1" data-path="appendixA.html"><a href="appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="appendixA.html"><a href="appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="appendixA.html"><a href="appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="appendixA.html"><a href="appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="appendixA.html"><a href="appendixA.html#appPercentiles"><i class="fa fa-check"></i><b>A.1.5</b> Percentiles or rank</a></li>
<li class="chapter" data-level="A.1.6" data-path="appendixA.html"><a href="appendixA.html#appDistributions"><i class="fa fa-check"></i><b>A.1.6</b> Distribution</a></li>
<li class="chapter" data-level="A.1.7" data-path="appendixA.html"><a href="appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.7</b> Outliers</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Projects</b></span></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html"><i class="fa fa-check"></i>Project 1</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#stories-from-the-atlas-describing-data-using-maps-regressions-and-correlations"><i class="fa fa-check"></i>Stories from the Atlas: Describing Data using Maps, Regressions, and Correlations</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#instructions"><i class="fa fa-check"></i>Instructions</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#specific-questions-to-address-in-your-narrative"><i class="fa fa-check"></i>Specific questions to address in your narrative</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#description"><i class="fa fa-check"></i>Data Description</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#cheatsheetproject1"><i class="fa fa-check"></i>Cheatsheat commands</a>
<ul>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#unweighted-summary-statistics"><i class="fa fa-check"></i>Unweighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#load-package"><i class="fa fa-check"></i>Load package</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#weighted-summary-statistics"><i class="fa fa-check"></i>Weighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#subset-observations"><i class="fa fa-check"></i>Subset observations</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#standardize-variables"><i class="fa fa-check"></i>Standardize variables</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#run-regression"><i class="fa fa-check"></i>Run regression</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#how-to-read-the-regression-output"><i class="fa fa-check"></i>How to read the regression output?</a></li>
<li class="chapter" data-level="" data-path="project1.html"><a href="project1.html#plotting-the-linear-relationship"><i class="fa fa-check"></i>Plotting the linear relationship</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html"><i class="fa fa-check"></i>Project 2</a>
<ul>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#do-smaller-classes-improve-test-scores-evidence-from-a-regression-discontinuity-design"><i class="fa fa-check"></i>Do Smaller Classes Improve Test Scores? Evidence from a Regression Discontinuity Design</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#instructions-1"><i class="fa fa-check"></i>Instructions</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#questions-to-address-in-your-replication"><i class="fa fa-check"></i>Questions to address in your replication</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#descriptionproject2"><i class="fa fa-check"></i>Data Description</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#cheatsheetproject2"><i class="fa fa-check"></i>Cheatsheat commands</a>
<ul>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#r-command-description"><i class="fa fa-check"></i>R command Description</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#packages-needed"><i class="fa fa-check"></i>Packages needed</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#subset-observations-1"><i class="fa fa-check"></i>Subset observations</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#draw-binned-scatterplots"><i class="fa fa-check"></i>Draw binned scatterplots</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#collapse-or-summarize-datasets"><i class="fa fa-check"></i>Collapse or summarize datasets</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#draw-graph-of-count-of-schools"><i class="fa fa-check"></i>Draw graph of count of schools</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#estimate-the-discontinuity"><i class="fa fa-check"></i>Estimate the discontinuity</a></li>
<li class="chapter" data-level="" data-path="project2.html"><a href="project2.html#interpretation"><i class="fa fa-check"></i>Interpretation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html"><i class="fa fa-check"></i>Project 3</a>
<ul>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#social-capital-and-economic-mobility"><i class="fa fa-check"></i>Social Capital and Economic Mobility</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#instructions-2"><i class="fa fa-check"></i>Instructions</a>
<ul>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#specific-questions-to-address-in-your-narrative-1"><i class="fa fa-check"></i>Specific questions to address in your narrative</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#data-description"><i class="fa fa-check"></i>Data Description</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#cheatsheetproject3"><i class="fa fa-check"></i>Cheatsheat commands</a>
<ul>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#unweighted-summary-statistics-1"><i class="fa fa-check"></i>Unweighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#load-package-1"><i class="fa fa-check"></i>Load package</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#weighted-summary-statistics-1"><i class="fa fa-check"></i>Weighted summary statistics</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#subset-observations-2"><i class="fa fa-check"></i>Subset observations</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#standardize-variables-1"><i class="fa fa-check"></i>Standardize variables</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#run-regression-1"><i class="fa fa-check"></i>Run regression</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#how-to-read-the-regression-output-1"><i class="fa fa-check"></i>How to read the regression output?</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#confidence-intervals"><i class="fa fa-check"></i>Confidence Intervals</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#plotting-the-linear-relationship-1"><i class="fa fa-check"></i>Plotting the linear relationship</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html"><i class="fa fa-check"></i>Project 4</a>
<ul>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#using-google-datacommons-to-predict-social-mobility"><i class="fa fa-check"></i>Using Google DataCommons to Predict Social Mobility</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#instructions-3"><i class="fa fa-check"></i>Instructions</a>
<ul>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#specific-questions"><i class="fa fa-check"></i>Specific questions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#data-description-1"><i class="fa fa-check"></i>Data Description</a></li>
<li class="chapter" data-level="" data-path="project3.html"><a href="project3.html#cheatsheetproject3"><i class="fa fa-check"></i>Cheatsheat commands</a>
<ul>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#how-to-tell-r-that-you-have-a-categorical-variable"><i class="fa fa-check"></i>How to tell R that you have a categorical variable?</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#load-package-2"><i class="fa fa-check"></i>Load package</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#run-regression-2"><i class="fa fa-check"></i>Run regression</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#measures-of-accuracy-in-prediction-in-a-multiple-regression"><i class="fa fa-check"></i>Measures of accuracy in prediction in a Multiple regression</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#estimating-a-decision-tree"><i class="fa fa-check"></i>Estimating a Decision Tree</a></li>
<li class="chapter" data-level="" data-path="project4.html"><a href="project4.html#measures-of-accuracy-in-a-decision-tree"><i class="fa fa-check"></i>Measures of accuracy in a Decision Tree</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://www.jmorenomedina.com/" target="blank">By Jon Moreno-Medina</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Economics of Public and Social Issues</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="viz" class="section level1 hasAnchor" number="12">
<h1><span class="header-section-number">Chapter 12</span> Data Visualization<a href="viz.html#viz" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<p>This chapter is based in big part on the <a href="https://nulib.github.io/moderndive_book/2-viz.html">chapter on visualization</a> by the folks at Northwestern. Please be check that link if you want to dive into how to make even cooler graphs than the ones we will cover here.</p>
</blockquote>
<p>We will learn basic tools to visualize our data. By visualizing our data, we gain valuable insights that we couldn’t initially see from just looking at the raw data in spreadsheet form. We will use the <code>ggplot2</code> package as it provides an easy way to customize your plots. <code>ggplot2</code> is rooted in the data visualization theory known as <em>The Grammar of Graphics</em> <span class="citation">(<a href="#ref-wilkinson2005"><strong>wilkinson2005?</strong></a>)</span>.</p>
<p>At the most basic level, graphics/plots/charts (we use these terms interchangeably in this guide) provide a nice way for us to get a sense for how quantitative variables compare in terms of their center (where the values tend to be located) and their spread (how they vary around the center). Graphics should be designed to emphasize the findings and insight you want your audience to understand. This does however require a balancing act. On the one hand, you want to highlight as many meaningful relationships and interesting findings as possible; on the other you don’t want to include so many as to overwhelm your audience.</p>
<p>As we will see, plots/graphics also help us to identify patterns in our data. We will see that a common extension of these ideas is to compare the <em>distribution</em> of one quantitative variable (i.e., what the spread of a variable looks like or how the variable is <em>distributed</em> in terms of its values) as we go across the levels of a different categorical variable.</p>
<div id="needed-data-and-packages" class="section level3 unnumbered hasAnchor">
<h3>Needed data and packages<a href="viz.html#needed-data-and-packages" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s load all the packages and data needed for this chapter (this assumes you’ve already installed them). Read Section <a href="getting-started.html#packages">11.6</a> for information on how to install and load R packages. As before, we will load the atlas dataset as well. We will also plot some of the information in the package <code>gapminder</code> for some of our examples.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="viz.html#cb11-1" tabindex="-1"></a>atlas <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="fu">gzcon</span>(<span class="fu">url</span>(<span class="st">&quot;https://raw.githubusercontent.com/jrm87/ECO3253_repo/master/data/atlas.rds&quot;</span>)))</span></code></pre></div>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="viz.html#cb12-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="viz.html#cb12-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb12-3"><a href="viz.html#cb12-3" tabindex="-1"></a><span class="fu">library</span>(gapminder)</span></code></pre></div>
<hr />
</div>
<div id="grammarofgraphics" class="section level2 hasAnchor" number="12.1">
<h2><span class="header-section-number">12.1</span> The Grammar of Graphics<a href="viz.html#grammarofgraphics" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We begin with a discussion of a theoretical framework for data visualization known as “The Grammar of Graphics,” which serves as the foundation for the <code>ggplot2</code> package. Think of how we construct sentences in English to form sentences by combining different elements, like nouns, verbs, particles, subjects, objects, etc. However, we can’t just combine these elements in any arbitrary order; we must do so following a set of rules known as a linguistic grammar. Similarly to a linguistic grammar, “The Grammar of Graphics” define a set of rules for constructing <em>statistical graphics</em> by combining different types of <em>layers</em>. This grammar was created by Leland Wilkinson <span class="citation">(<a href="#ref-wilkinson2005"><strong>wilkinson2005?</strong></a>)</span> and has been implemented in a variety of data visualization software including R.</p>
<div id="components-of-the-grammar" class="section level3 hasAnchor" number="12.1.1">
<h3><span class="header-section-number">12.1.1</span> Components of the Grammar<a href="viz.html#components-of-the-grammar" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In short, the grammar tells us that:</p>
<blockquote>
<p><strong>A statistical graphic is a <code>mapping</code> of <code>data</code> variables to <code>aes</code>thetic attributes of <code>geom</code>etric objects.</strong></p>
</blockquote>
<p>Specifically, we can break a graphic into the following three essential components:</p>
<ol style="list-style-type: decimal">
<li><code>data</code>: the data set composed of variables that we map.</li>
<li><code>geom</code>: the geometric object in question. This refers to the type of object we can observe in a plot. For example: points, lines, and bars.</li>
<li><code>aes</code>: aesthetic attributes of the geometric object. For example, x-position, y-position, color, shape, and size. Each assigned aesthetic attribute can be mapped to a variable in our data set.</li>
</ol>
<p>You might be wondering why we wrote the terms <code>data</code>, <code>geom</code>, and <code>aes</code> in a computer code type font. We’ll see very shortly that we’ll specify the elements of the grammar in R using these terms. However, let’s first break down the grammar with an example unrelated to our mobility data, but worry not! We will return to the atlas data. First…</p>
</div>
<div id="gapminder" class="section level3 hasAnchor" number="12.1.2">
<h3><span class="header-section-number">12.1.2</span> Gapminder data<a href="viz.html#gapminder" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In February 2006, a statistician named Hans Rosling gave a TED talk titled <a href="https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen">“The best stats you’ve ever seen”</a> where he presented global economic, health, and development data from the website <a href="http://www.gapminder.org/tools/#_locale_id=en;&amp;chart-type=bubbles">gapminder.org</a>. For example, for the 142 countries included from 2007, let’s consider only the first 6 countries when listed alphabetically in Table <a href="viz.html#tab:gapminder-2007">12.1</a>.</p>
<table class="table" style="font-size: 16px; color: black; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:gapminder-2007">Table 12.1: </span><span id="tab:gapminder-2007">Table 12.2: </span>Gapminder 2007 Data: First 6 of 142 countries
</caption>
<thead>
<tr>
<th style="text-align:left;">
Country
</th>
<th style="text-align:left;">
Continent
</th>
<th style="text-align:right;">
Life Expectancy
</th>
<th style="text-align:right;">
Population
</th>
<th style="text-align:right;">
GDP per Capita
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Afghanistan
</td>
<td style="text-align:left;">
Asia
</td>
<td style="text-align:right;">
43.8
</td>
<td style="text-align:right;">
31889923
</td>
<td style="text-align:right;">
975
</td>
</tr>
<tr>
<td style="text-align:left;">
Albania
</td>
<td style="text-align:left;">
Europe
</td>
<td style="text-align:right;">
76.4
</td>
<td style="text-align:right;">
3600523
</td>
<td style="text-align:right;">
5937
</td>
</tr>
<tr>
<td style="text-align:left;">
Algeria
</td>
<td style="text-align:left;">
Africa
</td>
<td style="text-align:right;">
72.3
</td>
<td style="text-align:right;">
33333216
</td>
<td style="text-align:right;">
6223
</td>
</tr>
<tr>
<td style="text-align:left;">
Angola
</td>
<td style="text-align:left;">
Africa
</td>
<td style="text-align:right;">
42.7
</td>
<td style="text-align:right;">
12420476
</td>
<td style="text-align:right;">
4797
</td>
</tr>
<tr>
<td style="text-align:left;">
Argentina
</td>
<td style="text-align:left;">
Americas
</td>
<td style="text-align:right;">
75.3
</td>
<td style="text-align:right;">
40301927
</td>
<td style="text-align:right;">
12779
</td>
</tr>
<tr>
<td style="text-align:left;">
Australia
</td>
<td style="text-align:left;">
Oceania
</td>
<td style="text-align:right;">
81.2
</td>
<td style="text-align:right;">
20434176
</td>
<td style="text-align:right;">
34435
</td>
</tr>
</tbody>
</table>
<p>Each row in this table corresponds to a country in 2007. For each row, we have 5 columns:</p>
<ol style="list-style-type: decimal">
<li><strong>Country</strong>: Name of country.</li>
<li><strong>Continent</strong>: Which of the five continents the country is part of. (Note that “Americas” includes countries in both North and South America and that Antarctica is excluded.)</li>
<li><strong>Life Expectancy</strong>: Life expectancy in years.</li>
<li><strong>Population</strong>: Number of people living in the country.</li>
<li><strong>GDP per Capita</strong>: Gross domestic product (in US dollars).</li>
</ol>
<p>Now consider Figure <a href="viz.html#fig:gapminder">12.1</a>, which plots this data for all 142 countries in the data.</p>
<!--
Note that R will deal with large numbers using scientific notation.  So in the legend for "Population", 1.25e+09 is 1.25 $\times$ 10^9^ = 1,250,000,000 = 1.25 billion. 
-->
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:gapminder"></span>
<img src="_main_files/figure-html/gapminder-1.png" alt="Life Expectancy over GDP per Capita in 2007" width="\textwidth" />
<p class="caption">
Figure 12.1: Life Expectancy over GDP per Capita in 2007
</p>
</div>
<p>Let’s view this plot through the grammar of graphics:</p>
<ol style="list-style-type: decimal">
<li>The <code>data</code> variable <strong>GDP per Capita</strong> gets mapped to the <code>x</code>-position <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Life Expectancy</strong> gets mapped to the <code>y</code>-position <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Population</strong> gets mapped to the <code>size</code> <code>aes</code>thetic of the points.</li>
<li>The <code>data</code> variable <strong>Continent</strong> gets mapped to the <code>color</code> <code>aes</code>thetic of the points.</li>
</ol>
<p>We’ll see shortly that <code>data</code> corresponds to the particular data frame where our data is saved and a “data variable” corresponds to a particular column in the data frame. Furthermore, the type of <code>geom</code>etric object considered in this plot are points. That being said, while in this example we are considering points, graphics are not limited to just points. Other plots involve lines while others involve bars.</p>
<p>Let’s summarize the three essential components of the Grammar in Table <a href="viz.html#tab:summary-table-gapminder">12.3</a>.</p>
<table class="table" style="font-size: 16px; color: black; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:summary-table-gapminder">Table 12.3: </span><span id="tab:summary-table-gapminder">Table 12.4: </span>Summary of Grammar of Graphics for this plot
</caption>
<thead>
<tr>
<th style="text-align:left;">
data variable
</th>
<th style="text-align:left;">
aes
</th>
<th style="text-align:left;">
geom
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
GDP per Capita
</td>
<td style="text-align:left;">
x
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Life Expectancy
</td>
<td style="text-align:left;">
y
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Population
</td>
<td style="text-align:left;">
size
</td>
<td style="text-align:left;">
point
</td>
</tr>
<tr>
<td style="text-align:left;">
Continent
</td>
<td style="text-align:left;">
color
</td>
<td style="text-align:left;">
point
</td>
</tr>
</tbody>
</table>
</div>
<div id="other-components" class="section level3 hasAnchor" number="12.1.3">
<h3><span class="header-section-number">12.1.3</span> Other components<a href="viz.html#other-components" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are other components of the Grammar of Graphics we can control as well. As you start to delve deeper into the Grammar of Graphics, you’ll start to encounter these topics more frequently. In this book however, we’ll keep things simple and only work with the two additional components listed below:</p>
<ul>
<li><code>facet</code>ing breaks up a plot into small multiples corresponding to the levels of another variable (Section <a href="#facets"><strong>??</strong></a>)</li>
<li><code>position</code> adjustments for barplots (Section <a href="viz.html#geombar">12.5</a>)</li>
</ul>
<!--
- `scales` that both
    + convert *data units* to *physical units* the computer can display. For example, apply a log-transformation on one of the axes to focus on multiplicative rather than additive changes.
    + draw a legend and/or axes, which provide an inverse mapping to make it possible to read the original data values from the graph.
- `coord`inate system for x/y values: typically `cartesian`, but can also be `map` or `polar`.
- `stat`istical transformations: this includes smoothing, binning values into a histogram, or no transformation at all (known as the `"identity"` transformation).
-->
<p>Other more complex components like <code>scales</code> and <code>coord</code>inate systems are left for a more advanced text such as <a href="http://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings">R for Data Science</a> <span class="citation">(<a href="#ref-rds2016"><strong>rds2016?</strong></a>)</span>. Generally speaking, the Grammar of Graphics allows for a high degree of customization of plots and also a consistent framework for easily updating and modifying them.</p>
</div>
<div id="ggplot2-package" class="section level3 hasAnchor" number="12.1.4">
<h3><span class="header-section-number">12.1.4</span> ggplot2 package<a href="viz.html#ggplot2-package" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this book, we will be using the <code>ggplot2</code> package for data visualization, which is an implementation of the Grammar of Graphics for R <span class="citation">(<a href="#ref-R-ggplot2"><strong>R-ggplot2?</strong></a>)</span>. As we noted earlier, a lot of the previous section was written in a computer code type font. This is because the various components of the Grammar of Graphics are specified in the <code>ggplot()</code> function included in the <code>ggplot2</code> package, which expects at a minimum as arguments (i.e. inputs):</p>
<ul>
<li>The data frame where the variables exist: the <code>data</code> argument.</li>
<li>The mapping of the variables to aesthetic attributes: the <code>mapping</code> argument which specifies the <code>aes</code>thetic attributes involved.</li>
</ul>
<p>After we’ve specified these components, we then add <em>layers</em> to the plot using the <code>+</code> sign. The most essential layer to add to a plot is the layer that specifies which type of <code>geom</code>etric object we want the plot to involve: points, lines, bars, and others. Other layers we can add to a plot include layers specifying the plot title, axes labels, visual themes for the plots, and facets (which we’ll see in Section <a href="#facets"><strong>??</strong></a>).</p>
<p>Let’s now put the theory of the Grammar of Graphics into practice.</p>
<hr />
</div>
</div>
<div id="FiveNG" class="section level2 hasAnchor" number="12.2">
<h2><span class="header-section-number">12.2</span> Three Important Graphs -<a href="viz.html#FiveNG" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In order to keep things simple, we will only focus on 3 types of graphics in this section, each with a commonly given name.</p>
<ol style="list-style-type: decimal">
<li>scatterplots</li>
<li>histograms</li>
<li>barplots</li>
</ol>
<p>We will discuss some variations of these plots, but with this basic repertoire of graphics in your toolbox you can visualize a wide array of different variable types. Note that certain plots are only appropriate for categorical variables and while others are only appropriate for quantitative variables. You’ll want to quiz yourself often as we go along on which plot makes sense a given a particular problem or data set.</p>
<hr />
</div>
<div id="scatterplots" class="section level2 hasAnchor" number="12.3">
<h2><span class="header-section-number">12.3</span> Scatterplots<a href="viz.html#scatterplots" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The simplest of the figrue we will cover are <em>scatterplots</em>, also called bivariate plots. They allow you to visualize the relationship between two numerical variables. While you may already be familiar with scatterplots, let’s view them through the lens of the Grammar of Graphics. Specifically, we will visualize the relationship across neighborhoods between the following two numerical variables in the <code>atlas</code> data frame:</p>
<ol style="list-style-type: decimal">
<li><code>kfr_pooled_p25</code>: upward mobility for children with parents on the percentile 25 on the horizontal “y” axis</li>
<li><code>med_hhinc2016</code>: median household income in 2016 on the vertical “x” axis</li>
</ol>
<div id="geompoint" class="section level3 hasAnchor" number="12.3.1">
<h3><span class="header-section-number">12.3.1</span> Scatterplots via geom_point<a href="viz.html#geompoint" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now go over the code that will create the desired scatterplot, keeping in mind our discussion on the Grammar of Graphics in Section <a href="viz.html#grammarofgraphics">12.1</a>. We’ll be using the <code>ggplot()</code> function included in the <code>ggplot2</code> package.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="viz.html#cb13-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> med_hhinc2016, <span class="at">y =</span> kfr_pooled_p25)) <span class="sc">+</span> </span>
<span id="cb13-2"><a href="viz.html#cb13-2" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p>Let’s break this down piece-by-piece:</p>
<ul>
<li>Within the <code>ggplot()</code> function, we specify two of the components of the Grammar of Graphics as arguments (i.e. inputs):
<ol style="list-style-type: decimal">
<li>The <code>data</code> frame to be <code>atlas</code> by setting <code>data = atlas</code>.</li>
<li>The <code>aes</code>thetic <code>mapping</code> by setting <code>aes(x = med_hhinc2016, y = kfr_pooled_p25)</code>. Specifically:
<ul>
<li>the variable <code>med_hhinc2016</code> maps to the <code>x</code> position aesthetic</li>
<li>the variable <code>kfr_pooled_p25</code> maps to the <code>y</code> position aesthetic</li>
</ul></li>
</ol></li>
<li>We add a layer to the <code>ggplot()</code> function call using the <code>+</code> sign. The layer in question specifies the third component of the grammar: the <code>geom</code>etric object. In this case the geometric object are points, set by specifying <code>geom_point()</code>.</li>
</ul>
<p>After running the above code, you’ll notice two outputs: a warning message and the graphic shown in Figure <a href="viz.html#fig:noalpha">12.2</a>. Let’s first unpack the warning message:
“y” axis</p>
<pre><code>## Warning: Removed 1372 rows containing missing values (`geom_point()`).</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:noalpha"></span>
<img src="_main_files/figure-html/noalpha-1.png" alt="Median Household Income in 2016 vs Mobility for Children with Parents in Percentile 25" width="\textwidth" />
<p class="caption">
Figure 12.2: Median Household Income in 2016 vs Mobility for Children with Parents in Percentile 25
</p>
</div>
<p>After running the above code, R returns a warning message alerting us to the fact that 1372 rows were ignored due to them being missing. For 1372 rows either the value for <code>med_hhinc2016</code> or <code>kfr_pooled_p25</code> or both were missing (recorded in R as <code>NA</code>), and thus these rows were ignored in our plot. Turning our attention to the resulting scatterplot in Figure <a href="viz.html#fig:noalpha">12.2</a>, we see that a positive relationship exists between <code>med_hhinc2016</code> and <code>kfr_pooled_p25</code>: as the median income level of the neighborhood increases, the mobility for children of parents in the percentile 25 tend to also increase.</p>
<p>Before we continue, let’s consider a few more notes on the layers in the above code that generated the scatterplot:</p>
<ul>
<li>Note that the <code>+</code> sign comes at the end of lines, and not at the beginning. You’ll get an error in R if you put it at the beginning.</li>
<li>When adding layers to a plot, you are encouraged to start a new line after the <code>+</code> so that the code for each layer is on a new line. As we add more and more layers to plots, you’ll see this will greatly improve the legibility of your code.</li>
<li>To stress the importance of adding layers in particular the layer specifying the <code>geom</code>etric object, consider Figure <a href="viz.html#fig:nolayers">12.3</a> where no layers are added. A not very useful plot!</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="viz.html#cb15-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> med_hhinc2016, <span class="at">y =</span> kfr_pooled_p25))</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:nolayers"></span>
<img src="_main_files/figure-html/nolayers-1.png" alt="Plot with No Layers" width="\textwidth" />
<p class="caption">
Figure 12.3: Plot with No Layers
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC3.1)</strong> What are some other features of the plot that stand out to you?</p>
<p><strong>(LC3.2)</strong> Create a new scatterplot using different variables in the <code>atlas</code> data frame by modifying the example above.</p>
<div class="learncheck">

</div>
</div>
<div id="overplotting" class="section level3 hasAnchor" number="12.3.2">
<h3><span class="header-section-number">12.3.2</span> Over-plotting<a href="viz.html#overplotting" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Sometimes you end up with a large mass of points, which can cause some confusion as it is hard to tell the true number of points that are plotted. This is the result of a phenomenon called <em>overplotting</em>. As one may guess, this corresponds to values being plotted on top of each other <em>over</em> and <em>over</em> again. It is often difficult to know just how many values are plotted in this way when looking at a basic scatterplot as we have here. The main methods to address the issue of overplotting is:</p>
<ul>
<li>By adjusting the transparency of the points.</li>
</ul>
<p><strong>Changing the transparency</strong></p>
<p>The main way of addressing overplotting is by changing the transparency of the points by using the <code>alpha</code> argument in <code>geom_point()</code>. By default, this value is set to <code>1</code>. We can change this to any value between <code>0</code> and <code>1</code>, where <code>0</code> sets the points to be 100% transparent and <code>1</code> sets the points to be 100% opaque. Note how the following code is identical to the code in Section <a href="viz.html#scatterplots">12.3</a> that created the scatterplot with overplotting, but with <code>alpha = 0.2</code> added to the <code>geom_point()</code>:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="viz.html#cb16-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> med_hhinc2016, <span class="at">y =</span> kfr_pooled_p25))<span class="sc">+</span></span>
<span id="cb16-2"><a href="viz.html#cb16-2" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:alpha"></span>
<img src="_main_files/figure-html/alpha-1.png" alt="Delay scatterplot with alpha=0.2" width="\textwidth" />
<p class="caption">
Figure 12.4: Delay scatterplot with alpha=0.2
</p>
</div>
<p>The key feature to note in Figure <a href="viz.html#fig:alpha">12.4</a> is that the transparency of the points is cumulative: areas with a high-degree of overplotting are darker, whereas areas with a lower degree are less dark. Note furthermore that there is no <code>aes()</code> surrounding <code>alpha = 0.2</code>. This is because we are not mapping a variable to an aesthetic attribute, but rather merely changing the default setting of <code>alpha</code>. In fact, you’ll receive an error if you try to change the second line above to read <code>geom_point(aes(alpha = 0.2))</code>.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC3.3)</strong> Why is setting the <code>alpha</code> argument value useful with scatterplots? What further information does it give you that a regular scatterplot cannot?</p>
<div class="learncheck">

</div>
</div>
<div id="summary" class="section level3 hasAnchor" number="12.3.3">
<h3><span class="header-section-number">12.3.3</span> Summary<a href="viz.html#summary" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Scatterplots display the relationship between two numerical variables. They are among the most commonly used plots because they can provide an immediate way to see the trend in one variable versus another. However, if you try to create a scatterplot where either one of the two variables is not numerical, you might get strange results. Be careful!</p>
<p>With medium to large data sets, you may need to play around with the different modifications one can make to a scatterplot. This tweaking is often a fun part of data visualization, since you’ll have the chance to see different relationships come about as you make subtle changes to your plots.</p>
<p>Last thing: remember Figure <a href="viz.html#fig:gapminder">12.1</a>? Here is the code of how we did that. It has a few pieces that you would need to figure out on your own, but you should get the essence by now. In particular, in the first line we pass on a filtered data for the year 2007. I’ll explain that more in the next Section <a href="wrangling.html#wrangling">13</a> on Data Wrangling. Still, try it out!</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="viz.html#cb17-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> gapminder<span class="sc">%&gt;%</span><span class="fu">filter</span>(year <span class="sc">==</span> <span class="dv">2007</span>), <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x=</span>gdpPercap, <span class="at">y=</span>lifeExp, <span class="at">size=</span>pop, <span class="at">col=</span>continent)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="viz.html#cb17-2" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb17-3"><a href="viz.html#cb17-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;GDP per capita&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Life expectancy&quot;</span>)</span></code></pre></div>
<hr />
</div>
</div>
<div id="histograms" class="section level2 hasAnchor" number="12.4">
<h2><span class="header-section-number">12.4</span> Histograms<a href="viz.html#histograms" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s consider the <code>kfr_pooled_p25</code> variable in the <code>atlas</code> data frame once again, but now we want to understand how the values of <code>kfr_pooled_p25</code> <em>distribute</em>. In other words, for economic mobility for children from parents in the percentile 25:</p>
<ol style="list-style-type: decimal">
<li>What are the smallest and largest values?</li>
<li>What is the “center” value?</li>
<li>How do the values spread out?</li>
<li>What are frequent and infrequent values?</li>
</ol>
<p>One way to visualize this <em>distribution</em> of this single variable <code>kfr_pooled_p25</code> is to plot what is know as a <em>histogram</em>. A histogram is a plot that visualizes the <em>distribution</em> of a numerical value as follows:</p>
<ol style="list-style-type: decimal">
<li>We first cut up the x-axis into a series of <em>bins</em>, where each bin represents a range of values.</li>
<li>For each bin, we count the number of observations that fall in the range corresponding to that bin.</li>
<li>Then for each bin, we draw a bar whose height marks the corresponding count.</li>
</ol>
<p>Let’s drill-down on an example of a histogram, shown in Figure <a href="viz.html#fig:histogramexample">12.5</a>.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:histogramexample"></span>
<img src="_main_files/figure-html/histogramexample-1.png" alt="Example histogram." width="\textwidth" />
<p class="caption">
Figure 12.5: Example histogram.
</p>
</div>
<p>Observe that there are six bins of equal width between $ 30,000 and $ 60,000, thus we have three bins of width $ 5,000 each: one bin for the 30-35k range, and so on, until the bin for the 55-60k range. Since:</p>
<ol style="list-style-type: decimal">
<li>The bin for the 30-35k range has a height of around 9000, this histogram is telling us that around 9000 neighborhoods in the US have an average mobility measure for children of parents in the percentile 25th of between $30,000 and $35,000.</li>
</ol>
<p>The remaining bins all have a similar interpretation.</p>
<div id="geomhistogram" class="section level3 hasAnchor" number="12.4.1">
<h3><span class="header-section-number">12.4.1</span> Histograms via geom_histogram<a href="viz.html#geomhistogram" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now present the <code>ggplot()</code> code to plot your first histogram! Unlike with scatterplots and linegraphs, there is now only one variable being mapped in <code>aes()</code>: the single numerical variable <code>temp</code>. The y-aesthetic of a histogram gets computed for you automatically. Furthermore, the geometric object layer is now a <code>geom_histogram()</code></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="viz.html#cb18-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="viz.html#cb18-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<pre><code>## Warning: Removed 1267 rows containing non-finite values (`stat_bin()`).</code></pre>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:weather-histogram"></span>
<img src="_main_files/figure-html/weather-histogram-1.png" alt="Histogram of mobility for children of p25 in the US." width="\textwidth" />
<p class="caption">
Figure 12.6: Histogram of mobility for children of p25 in the US.
</p>
</div>
<p>Let’s unpack the messages R sent us first. The first message is telling us that the histogram was constructed using <code>bins = 30</code>, in other words 30 equally spaced bins. This is known in computer programming as a default value; unless you override this default number of bins with a number you specify, R will choose 30 by default. We’ll see in the next section how to change this default number of bins. The second message is telling us once again that there are some missing values: that because one row has a missing <code>NA</code> value for <code>kfr_pooled_p25</code>, it was omitted from the histogram. R is just giving us a friendly heads up that this was the case.</p>
<p>Now’s let’s unpack the resulting histogram in Figure <a href="viz.html#fig:weather-histogram">12.6</a>. Observe that values less than $12,000 as well as values above $80,000 are rather rare. However, because of the large number of bins, its hard to get a sense for which range of temperatures is covered by each bin; everything is one giant amorphous blob. So let’s add white vertical borders demarcating the bins by adding a <code>color = "white"</code> argument to <code>geom_histogram()</code>:</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="viz.html#cb21-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb21-2"><a href="viz.html#cb21-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:weather-histogram-2"></span>
<img src="_main_files/figure-html/weather-histogram-2-1.png" alt="Histogram of mobility for children of p25 in the US with white borders." width="\textwidth" />
<p class="caption">
Figure 12.7: Histogram of mobility for children of p25 in the US with white borders.
</p>
</div>
<p>We can now better associate ranges of mobility to each of the bins. We can also vary the color of the bars by setting the <code>fill</code> argument. Run <code>colors()</code> to see all 657 possible choice of colors!</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="viz.html#cb22-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="viz.html#cb22-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">fill =</span> <span class="st">&quot;steelblue&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:weather-histogram-3"></span>
<img src="_main_files/figure-html/weather-histogram-3-1.png" alt="Histogram of mobility for children of p25 in the US with white borders." width="\textwidth" />
<p class="caption">
Figure 12.8: Histogram of mobility for children of p25 in the US with white borders.
</p>
</div>
</div>
<div id="adjustbins" class="section level3 hasAnchor" number="12.4.2">
<h3><span class="header-section-number">12.4.2</span> Adjusting the bins<a href="viz.html#adjustbins" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s now adjust the number of bins in our histogram in one of two methods:</p>
<ol style="list-style-type: decimal">
<li>By adjusting the number of bins via the <code>bins</code> argument to <code>geom_histogram()</code>.</li>
<li>By adjusting the width of the bins via the <code>binwidth</code> argument to <code>geom_histogram()</code>.</li>
</ol>
<p>Using the first method, we have the power to specify how many bins we would like to cut the x-axis up in. As mentioned in the previous section, the default number of bins is 30. We can override this default, to say 40 bins, as follows:</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="viz.html#cb23-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="viz.html#cb23-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">40</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-73"></span>
<img src="_main_files/figure-html/unnamed-chunk-73-1.png" alt="Histogram with 40 bins." width="\textwidth" />
<p class="caption">
Figure 12.9: Histogram with 40 bins.
</p>
</div>
<p>Using the second method, instead of specifying the number of bins, we specify the width of the bins by using the <code>binwidth</code> argument in the <code>geom_histogram()</code> layer. For example, let’s set the width of each bin to be 10°F.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="viz.html#cb24-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> kfr_pooled_p25)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="viz.html#cb24-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">4000</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>)</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-74"></span>
<img src="_main_files/figure-html/unnamed-chunk-74-1.png" alt="Histogram with binwidth 10." width="\textwidth" />
<p class="caption">
Figure 12.10: Histogram with binwidth 10.
</p>
</div>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC3.4)</strong> What does changing the number of bins from 30 to 40 tell us about the distribution of mobility?</p>
<p><strong>(LC3.5)</strong> Would you classify the distribution of mobility as symmetric or skewed?</p>
<p><strong>(LC3.6)</strong> What would you guess is the “center” value in this distribution? Why did you make that choice?</p>
<p><strong>(LC3.7)</strong> Is this data spread out greatly from the center or is it close? Why?</p>
<div class="learncheck">

</div>
</div>
<div id="summary-1" class="section level3 hasAnchor" number="12.4.3">
<h3><span class="header-section-number">12.4.3</span> Summary<a href="viz.html#summary-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Histograms, unlike scatterplots, present information on only a single numerical variable. Specifically, they are visualizations of the distribution of the numerical variable in question.</p>
<hr />
</div>
</div>
<div id="geombar" class="section level2 hasAnchor" number="12.5">
<h2><span class="header-section-number">12.5</span> Barplots<a href="viz.html#geombar" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Histograms are tools to visualize the distribution of numerical variables. Another common task is visualize the distribution of a categorical variable. This is a simpler task, as we are simply counting different categories, also known as <em>levels</em>, of a categorical variable. Often the best way to visualize these different counts, also known as <em>frequencies</em>, is with a barplot (also known as a barchart). One complication, however, is how your data is represented: is the categorical variable of interest “pre-counted” or not? For example, run the following code that manually creates two data frames representing a collection of fruit: 3 apples and 2 oranges.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="viz.html#cb25-1" tabindex="-1"></a>fruits <span class="ot">&lt;-</span> <span class="fu">data_frame</span>(</span>
<span id="cb25-2"><a href="viz.html#cb25-2" tabindex="-1"></a>  <span class="at">fruit =</span> <span class="fu">c</span>(<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>, <span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>)</span>
<span id="cb25-3"><a href="viz.html#cb25-3" tabindex="-1"></a>)</span>
<span id="cb25-4"><a href="viz.html#cb25-4" tabindex="-1"></a>fruits_counted <span class="ot">&lt;-</span> <span class="fu">data_frame</span>(</span>
<span id="cb25-5"><a href="viz.html#cb25-5" tabindex="-1"></a>  <span class="at">fruit =</span> <span class="fu">c</span>(<span class="st">&quot;apple&quot;</span>, <span class="st">&quot;orange&quot;</span>),</span>
<span id="cb25-6"><a href="viz.html#cb25-6" tabindex="-1"></a>  <span class="at">number =</span> <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">2</span>)</span>
<span id="cb25-7"><a href="viz.html#cb25-7" tabindex="-1"></a>)</span></code></pre></div>
<p>We see both the <code>fruits</code> and <code>fruits_counted</code> data frames represent the same collection of fruit. Whereas <code>fruits</code> just lists the fruit individually…</p>
<pre><code>## # A tibble: 5 × 1
##   fruit 
##   &lt;chr&gt; 
## 1 apple 
## 2 apple 
## 3 orange
## 4 apple 
## 5 orange</code></pre>
<p>… <code>fruits_counted</code> has a variable <code>count</code> which represents pre-counted values of each fruit.</p>
<pre><code>## # A tibble: 2 × 2
##   fruit  number
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 apple       3
## 2 orange      2</code></pre>
<p>Depending on how your categorical data is represented, you’ll need to use add a different <code>geom</code> layer to your <code>ggplot()</code> to create a barplot, as we now explore.</p>
<div id="barplots-via-geom_bar-or-geom_col" class="section level3 hasAnchor" number="12.5.1">
<h3><span class="header-section-number">12.5.1</span> Barplots via geom_bar or geom_col<a href="viz.html#barplots-via-geom_bar-or-geom_col" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s generate barplots using these two different representations of the same basket of fruit: 3 apples and 2 oranges. Using the <code>fruits</code> data frame where all 5 fruits are listed individually in 5 rows, we map the <code>fruit</code> variable to the x-position aesthetic and add a <code>geom_bar()</code> layer.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="viz.html#cb28-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> fruits, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> fruit)) <span class="sc">+</span></span>
<span id="cb28-2"><a href="viz.html#cb28-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:geombar"></span>
<img src="_main_files/figure-html/geombar-1.png" alt="Barplot when counts are not pre-counted" width="\textwidth" />
<p class="caption">
Figure 12.11: Barplot when counts are not pre-counted
</p>
</div>
<p>However, using the <code>fruits_counted</code> data frame where the fruit have been “pre-counted”, we map the <code>fruit</code> variable to the x-position aesthetic as with <code>geom_bar()</code>, but we also map the <code>count</code> variable to the y-position aesthetic, and add a <code>geom_col()</code> layer.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="viz.html#cb29-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> fruits_counted, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> fruit, <span class="at">y =</span> number)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="viz.html#cb29-2" tabindex="-1"></a>  <span class="fu">geom_col</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:geomcol"></span>
<img src="_main_files/figure-html/geomcol-1.png" alt="Barplot when counts are pre-counted" width="\textwidth" />
<p class="caption">
Figure 12.12: Barplot when counts are pre-counted
</p>
</div>
<p>Compare the barplots in Figures <a href="viz.html#fig:geombar">12.11</a> and <a href="viz.html#fig:geomcol">12.12</a>. They are identical because they reflect count of the same 5 fruit. However depending on how our data is saved, either pre-counted or not, we must add a different <code>geom</code> layer. When the categorical variable whose distribution you want to visualize is:</p>
<ul>
<li>Is not pre-counted in your data frame: use <code>geom_bar()</code>.</li>
<li>Is pre-counted in your data frame, use <code>geom_col()</code> with the y-position aesthetic mapped to the variable that has the counts.</li>
</ul>
<p>Let’s now go back to the <code>atlas</code> data frame and visualize the distribution of the categorical variable <code>state</code>. In other words, let’s visualize the number of neighborhoodsin the data belonging to each state. Recall from Section <a href="getting-started.html#exploredataframes">11.7.4</a> when you first explored the <code>atlas</code> data frame you saw that each row corresponds to a neighborhood. In other words the <code>atlas</code> data frame is more like the <code>fruits</code> data frame than the <code>fruits_counted</code> data frame above, and thus we should use <code>geom_bar()</code> instead of <code>geom_col()</code> to create a barplot. Much like a <code>geom_histogram()</code>, there is only one variable in the <code>aes()</code> aesthetic mapping: the variable <code>state</code> gets mapped to the <code>x</code>-position.</p>

<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="viz.html#cb30-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> state)) <span class="sc">+</span></span>
<span id="cb30-2"><a href="viz.html#cb30-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:flightsbar"></span>
<img src="_main_files/figure-html/flightsbar-1.png" alt="Number of neighborhoods by State in the atlas data using geom_bar" width="\textwidth" />
<p class="caption">
Figure 12.13: Number of neighborhoods by State in the atlas data using geom_bar
</p>
</div>
<p>Observe in Figure <a href="viz.html#fig:flightsbar">12.13</a> that state 06, which is California, has the most number of neighborhoods in the data. If you don’t know which State FIPS code correspond to which State, you can see it <a href="https://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs143_013696">here</a>. For example: TX is State 48, while NC is State 37.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC3.8)</strong> Why are histograms inappropriate for visualizing categorical variables?</p>
<p><strong>(LC3.9)</strong> What is the difference between histograms and barplots?</p>
<p><strong>(LC3.10)</strong> How many neighborhoods are there in Texas in the atlas data?</p>
<div class="learncheck">

</div>
</div>
<div id="summary-2" class="section level3 hasAnchor" number="12.5.2">
<h3><span class="header-section-number">12.5.2</span> Summary<a href="viz.html#summary-2" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Barplots are the preferred way of displaying the distribution of a categorical variable, or in other words the frequency with which the different categories called <em>levels</em> occur. They are easy to understand and make it easy to make comparisons across levels. When trying to visualize two categorical variables, you have many options: stacked barplots, side-by-side barplots, and faceted barplots. Depending on what aspect of the joint distribution you are trying to emphasize, you will need to make a choice between these three types of barplots.</p>
<hr />
</div>
</div>
<div id="conclusion-2" class="section level2 hasAnchor" number="12.6">
<h2><span class="header-section-number">12.6</span> Conclusion<a href="viz.html#conclusion-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="summary-table" class="section level3 hasAnchor" number="12.6.1">
<h3><span class="header-section-number">12.6.1</span> Summary table<a href="viz.html#summary-table" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let’s recap all five of the three main figures in Table <a href="#tab:viz-summary-table"><strong>??</strong></a> summarizing their differences. Using these 5NG, you’ll be able to visualize the distributions and relationships of variables contained in a wide array of datasets.</p>
</div>
<div id="argument-specification" class="section level3 hasAnchor" number="12.6.2">
<h3><span class="header-section-number">12.6.2</span> Argument specification<a href="viz.html#argument-specification" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Run the following two segments of code. First this:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="viz.html#cb31-1" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> atlas, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> state)) <span class="sc">+</span></span>
<span id="cb31-2"><a href="viz.html#cb31-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p>then this:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="viz.html#cb32-1" tabindex="-1"></a><span class="fu">ggplot</span>(atlas, <span class="fu">aes</span>(<span class="at">x =</span> state)) <span class="sc">+</span></span>
<span id="cb32-2"><a href="viz.html#cb32-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p>You’ll notice that that both code segments create the same barplot, even though in the second segment we omitted the <code>data =</code> and <code>mapping =</code> code argument names. This is because the <code>ggplot()</code> by default assumes that the <code>data</code> argument comes first and the <code>mapping</code> argument comes second. So as long as you specify the data frame in question first and the <code>aes()</code> mapping second, you can omit the explicit statement of the argument names <code>data =</code> and <code>mapping =</code>.</p>
<p>Going forward for the rest of this book, all <code>ggplot()</code> will be like the second segment above: with the <code>data =</code> and <code>mapping =</code> explicit naming of the argument omitted and the default ordering of arguments respected.</p>
</div>
<div id="additional-resources-1" class="section level3 hasAnchor" number="12.6.3">
<h3><span class="header-section-number">12.6.3</span> Additional resources<a href="viz.html#additional-resources-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<!-- An R script file of all R code used in this chapter is available [here](scripts/03-visualization.R). -->
<p>If you want to further unlock the power of the <code>ggplot2</code> package for data visualization, you can check out RStudio’s “Data Visualization with ggplot2” cheatsheet. This cheatsheet summarizes much more than what we’ve discussed in this chapter, in particular the many more than the 3 <code>geom</code> geometric objects we covered in this Chapter, while providing quick and easy to read visual descriptions.</p>
<p>You can access this cheatsheet by going to the RStudio Menu Bar -&gt; Help -&gt; Cheatsheets -&gt; “Data Visualization with ggplot2”:</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:ggplot-cheatsheet"></span>
<img src="images/ggplot_cheatsheet-1.png" alt="Data Visualization with ggplot2 cheatsheat" width="\textwidth" />
<p class="caption">
Figure 12.14: Data Visualization with ggplot2 cheatsheat
</p>
</div>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="getting-started.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="wrangling.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-visualization.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
